const baseStatsByClass = {
  Samurai: {
    Strength: 50,
    Intelligence: 45,
    Speed: 80,
    Defense: 40,
    HP: 40,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  Wrestler: {
    Strength: 70,
    Intelligence: 25,
    Speed: 50,
    Defense: 50,
    HP: 70,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  Paladin: {
    Strength: 70,
    Intelligence: 45,
    Speed: 40,
    Defense: 60,
    HP: 80,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  Knight: {
    Strength: 80,
    Intelligence: 35,
    Speed: 50,
    Defense: 70,
    HP: 70,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  Scout: {
    Strength: 30,
    Intelligence: 55,
    Speed: 80,
    Defense: 40,
    HP: 50,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  Ninja: {
    Strength: 45,
    Intelligence: 40,
    Speed: 80,
    Defense: 50,
    HP: 40,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  MagiWhite: {
    Strength: 10,
    Intelligence: 90,
    Speed: 20,
    Defense: 35,
    HP: 35,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  MagiBlack: {
    Strength: 10,
    Intelligence: 85,
    Speed: 30,
    Defense: 30,
    HP: 35,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  MagiRed: {
    Strength: 10,
    Intelligence: 70,
    Speed: 35,
    Defense: 35,
    HP: 40,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },

  Priest: {
    Strength: 30,
    Intelligence: 60,
    Speed: 50,
    Defense: 35,
    HP: 70,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Monk: {
    Strength: 80,
    Intelligence: 40,
    Speed: 30,
    Defense: 45,
    HP: 70,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  BeastMaster: {
    Strength: 60,
    Intelligence: 20,
    Speed: 50,
    Defense: 65,
    HP: 80,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  Tracker: {
    Strength: 50,
    Intelligence: 70,
    Speed: 40,
    Defense: 65,
    HP: 40,
    BG: "/FighterBG.png",
    Icon: "/HeroIcon.png",
  },
  Fighter: {
    Strength: 60,
    Intelligence: 10,
    Speed: 20,
    Defense: 55,
    HP: 40,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },

  Cleric: {
    Strength: 20,
    Intelligence: 70,
    Speed: 20,
    Defense: 35,
    HP: 30,
    BG: "/ClericBG.png",
    Icon: "/ClericIcon.png",
  },
  Mage: {
    Strength: 5,
    Intelligence: 70,
    Speed: 20,
    Defense: 25,
    HP: 20,
    BG: "/MageBG.png",
    Icon: "/MageIcon.png",
  },
  Archmage: {
    Strength: 10,
    Intelligence: 90,
    Speed: 45,
    Defense: 45,
    HP: 50,
    BG: "/FighterBG.png",
    Icon: "/MageIcon.png",
  },
  Archer: {
    Strength: 35,
    Intelligence: 35,
    Speed: 50,
    Defense: 35,
    HP: 30,
    BG: "/ArcherBG.png",
    Icon: "/ArcherIcon.png",
  },
  Rogue: {
    Strength: 30,
    Intelligence: 40,
    Speed: 60,
    Defense: 25,
    HP: 30,
    BG: "/RogueBG.png",
    Icon: "/RogueIcon.png",
  },
  Summoner: {
    Strength: 20,
    Intelligence: 50,
    Speed: 10,
    Defense: 45,
    HP: 40,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Fairy: {
    Strength: 15,
    Intelligence: 60,
    Speed: 40,
    Defense: 35,
    HP: 25,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Elemental: {
    Strength: 10,
    Intelligence: 60,
    Speed: 20,
    Defense: 30,
    HP: 30,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Ranger: {
    Strength: 40,
    Intelligence: 40,
    Speed: 40,
    Defense: 40,
    HP: 40,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Giant: {
    Strength: 50,
    Intelligence: 5,
    Speed: 15,
    Defense: 65,
    HP: 50,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Vampire: {
    Strength: 60,
    Intelligence: 60,
    Speed: 60,
    Defense: 25,
    HP: 25,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  WereWolf: {
    Strength: 50,
    Intelligence: 15,
    Speed: 37,
    Defense: 35,
    HP: 20,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  DemiGod: {
    Strength: 90,
    Intelligence: 90,
    Speed: 30,
    Defense: 45,
    HP: 30,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Valkyrie: {
    Strength: 50,
    Intelligence: 40,
    Speed: 50,
    Defense: 45,
    HP: 30,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Witch: {
    Strength: 12,
    Intelligence: 50,
    Speed: 32,
    Defense: 25,
    HP: 22,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Satyr: {
    Strength: 43,
    Intelligence: 34,
    Speed: 40,
    Defense: 35,
    HP: 40,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Centaur: {
    Strength: 50,
    Intelligence: 20,
    Speed: 40,
    Defense: 45,
    HP: 50,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
  Android: {
    Strength: 80,
    Intelligence: 70,
    Speed: 40,
    Defense: 35,
    HP: 40,
    BG: "/FighterBG.png",
    Icon: "/FighterIcon.png",
  },
};
export default baseStatsByClass;
